rois = begonia.processing.roi.load_processed_signals(ts);
ns = rois(rois.type == "NS",:);
somas = cell2mat(ns.signal_raw);
donut = cell2mat(ns.signal_doughnut);
sub = cell2mat(ns.signal_subtracted_dff);

% Decompose signal using the MODWT

% Generated by MATLAB(R) 9.12 and Wavelet Toolbox 6.1.
% Generated on: 21-Oct-2022 03:21:20
% Logical array for selecting reconstruction elements
levelForReconstruction_s =  [false,true,false,false,true,true,true,true,true,true,true];
levelForReconstruction_d = [false,false,false,false,true,true,true,true,true,true,true];

for i = 1:size(somas,1)
    % Perform the decomposition using modwt
    wt = modwt(somas(i,:),'sym6',10);
    wt2 = modwt(donut(i,:),'sym6',10);

    % Construct MRA matrix using modwtmra
    mra = modwtmra(wt,'sym6');
    mra2 = modwtmra(wt2,'sym6');

    % Sum down the rows of the selected multiresolution signals
    somas_filt(i,:) = sum(mra(levelForReconstruction_s,:),1);
    donut_filt(i,:) = sum(mra2(levelForReconstruction_d,:),1);
end

% Subtraction 1
somas_sub = somas_filt - donut_filt;

% Subtraction 2
% for i = 1:size(somas,1)
%     y = somas(i,:)';
%     X = donut_filt(i,:)';
% 
%     b = (X'*X)\(X'*y);
%     y_hat = (X * b);
%     trace = (y - y_hat);
%     f0 = prctile(sgolayfilt(y,1,151),10);
%     dF(i,:) = trace/f0;
% end


dF_traces = somas_sub;

wd = 5 * fps;

% smooth trace
ftraces = sgolayfilt(dF_traces,1,wd+1,[],2);

% calculate baseline
F0 = prctile(ftraces,10,2)'; %8

% dff
deltaFoF = (dF_traces-F0')./F0';
dF_traces = deltaFoF;


for i = 1:size(dF_traces,1)
    dF_traces(i,:) = smooth(dF_traces(i,:));
end


