function dsignal = mra_dnoise(signal,level)

if nargin < 2, level = 8; end

l = false(1,13);
l(1:level) = true;
l = flip(l);

% Decompose signal using the MODWT

% Generated by MATLAB(R) 9.14 and Wavelet Toolbox 6.3.
% Generated on: 06-Aug-2023 03:58:58

% Logical array for selecting reconstruction elements
levelForReconstruction = l;

% Perform the decomposition using modwt
wt = modwt(signal,'sym4',12);

% Construct MRA matrix using modwtmra
mra = modwtmra(wt,'sym4');

% Sum down thegnal rows of the selected multiresolution signals
dsignal = sum(mra(levelForReconstruction,:),1);

end