function ns_denoise = denoise(neurons)


% Decompose signal using the MODWT

% Generated by MATLAB(R) 9.14 and Wavelet Toolbox 6.3.
% Generated on: 04-Aug-2023 04:07:25

% Logical array for selecting reconstruction elements
levelForReconstruction = [false,false,true,false,false,false,true,true,true,true];

% Perform the decomposition using modwt

ns_denoise = zeros(size(neurons,1),size(neurons,2));
for i = 1:size(neurons)

    ns = neurons(i,:);

    wt = modwt(ns,'sym4',9);

    % Construct MRA matrix using modwtmra
    mra = modwtmra(wt,'sym4');

    % Sum down the rows of the selected multiresolution signals
    ns1 = sum(mra(levelForReconstruction,:),1);

    ns_denoise(i,:) = ns1;
end
end